### PR TITLE
remove unused items

### LINKED ISSUE #139: Remove certain Inputs
Now that we move away from excel we could think about dropping some of the things from there for keeping the UI cleaner.

I think the following could just be added as a Bemerkung, or dropped entirely:
- Pfand einbehalten (rental)
- Grund (rental)
- Verpackung (item)
- Anleitung (item)

"Pfand einbehalten" is something that can be infered anyway from "Pfand zurück" I guess? They have been added by someone in the last half year anyway, and I don't have the feeling they have been used consistently or are that useful after all.

What do you think?

### PR DESCRIPTION
**Pull request by skjerns**
closes #139 

this removes
- deposit retained
- deposit retained reason
- manual
- packaging

### CODE REVIEW

**Comment by daniel17903** [comment]
You also need to remove them from the tables. This can be done in TableEditors/Items/Columns and TableEditors/Rentals/Columns

**Comment by skjerns** [comment]
Ah sure, thanks! Done.

**Comment by daniel17903** [comment]
TableEditors/Items/Columns is still missing

**Comment by skjerns** [comment]
ah, I could swear I also changed it there - nv, did it now!

**Pull request merged**
